### ISSUE TITLE
streamline the table view and make it possible to search

### ISSUE THREAD

**Issue by PKuhlmay** [krausandre/content-blocks-gui#4]
Maybe the table view for the overview could be inside one big table with some kind of filtering and sorting

- [x] make the table searchable
- [NO] show all elements in only one table (discuss this first)
- [x] try to make all columns one size

**Comment by krausandre** [comment]
IMHO, since this are different types, it should be separated tables.

**Comment by PKuhlmay** [comment]
I'll close this for now as we keep the different tables
